### PR TITLE
Initial XOAUTH2 implementation

### PR DESCRIPTION
**Pull request by cscorley**
Hi,

Opening this pull request for comments from the community. Not sure at the direction I've taken and would advice on what else to add so this makes it to the master branch.

To use you will need:

1. A Google OAuth2 client registered: https://developers.google.com/accounts/docs/OAuth2Login#registeringyourapp
    - Be sure to change the default project name (under project Settings)
    - You will need from this page:
        - client_id
        - client_secret
2. An email with this client authorized, namely the refresh_token, from performing an authentication. Easiest thing to do is to follow the steps here https://code.google.com/p/google-mail-oauth2-tools/wiki/OAuth2DotPyRunThrough

In your Repository, set the following configuration options:

    [Repository gmail-remote]
    type = Gmail
    remoteuser = <you>@gmail.com
    oauth2_client_id = <your_client_id>
    oauth2_client_secret = <your_client_secret>
    oauth2_refresh_token = <your_refresh_token_for_remoteuser>

Should be ready to rock. This method may work on other IMAPs that support AUTH=XOAUTH2, but I have no server other than Gmail to test on. I've tested that this method also works for Google Apps Gmail accounts.

### CODE REVIEW

**Comment by nicolas33** [comment]
Please, see #152.

**Comment by Frizlab** [comment]
This works for me! :)

**Comment by Frizlab** [comment]
If someone is interested, I can try and rebase this commit on the master of offlineimap, then make a new (reference) pull request.

**Comment by cscorley** [comment]
@Frizlab Go for it, I have no plans to work on this any longer.

**Comment by Roguelazer** [comment]
I rebased this on master a few weeks ago; it's at https://github.com/Roguelazer/offlineimap/tree/gmail-oauth if anyone wants it.

**Comment by Frizlab** [comment]
Rebased and signed off here: #254.

**Comment by nicolas33** [comment]
Closing this one since it moved to #254.

**Pull request closed without merging**
