### PR TITLE
Allow authorization via XOAUTH2 using access token

### PR DESCRIPTION
**Pull request by ojab**

### CODE REVIEW

**Comment by nicolas33** [comment]
Please insert documentation in `offlineimap.conf`.

**Comment by ojab** [comment]
Done.

**Comment by nicolas33** [comment]
Nice. Send me your sign-off, please. http://offlineimap.org/doc/dco.html

**Comment by ojab** [comment]
Done!

**Comment by nicolas33** [comment]
Thank you. Applied.

**Pull request closed without merging**
