### PR TITLE
New mail hook

### PR DESCRIPTION
**Pull request by krafczyk**
Second try at resolving #236.

### CODE REVIEW

**Comment by krafczyk** [comment]
Sorry about the last pull request.

I hope I've fixed all the problems this time.

**Comment by nicolas33** [comment]
You can squash both patches. Please, update offlineimap.conf accordingly and mark this feature as experimental.
Thank you.

**Comment by krafczyk** [comment]
Where do I mark the feature as experimental?

Next to the entry in offlineimap.conf?

**Comment by nicolas33** [comment]
Yes, in offlineimap.conf. :-)

**Comment by krafczyk** [comment]
Okay, I've squashed the commits, and added the relevant section to offlineimap.conf.

**Comment by nicolas33** [comment]
Thank you ! Applied. :-)

**Pull request closed without merging**
