### PR TITLE
Correction of typo in line 53

### PR DESCRIPTION
**Pull request by iamprakashom**
### Peer reviews

- [x] I've read the [DCO](http://www.offlineimap.org/doc/dco.html).
- [x] I've read the [Coding Guidelines](http://www.offlineimap.org/doc/CodingGuidelines.html)
- [x] The relevant informations about the changes stands in the commit message, not here in the message of the pull request.
- [x] Code changes follow the style of the files they change.
- [] Code is tested (provide details).

### CODE REVIEW

**Comment by nicolas33** [comment]
"in line N" does not make sense when introspecting history.
What would make sense is how important are the fix or the nature of the fixes.

Usually, I just put "filename: minor typo fix". It's enough for anyone looking forward the history it can easily be skipped since it's not important.

**Comment by iamprakashom** [comment]
[patch](https://github.com/iamprakashom/offlineimap/commit/155d7b7704547412797737ac536ecd5a1bb428e1) updated!

**Comment by nicolas33** [comment]
Looks correct. Care to squash both patches?

**Comment by nicolas33** [comment]
Applied with some little changes. Thanks!

**Comment by iamprakashom** [comment]
Thank for merging! :+1:

**Pull request closed without merging**
