### PR TITLE
Doc cleanup

### PR DESCRIPTION
**Pull request by mineo**
I'll just throw several things into this pull request because the changes themselves are each quite small.

This fixes several broken sphinx in the documentation, namely references to a make target `dev-doc` which doesn't exist anymore, broken RST markup (`:para` instead of `:param` and not properly escaped backslashes).

### CODE REVIEW

**Comment by nicolas33** [comment]
I merged first two patches. I didn't understand why the last one. Why is the current backslashing wrong?

**Comment by mineo** [comment]
The following picture shows how the documentation (built with sphinx 1.2.3) of `addmessageheader` looks like without the patch. The [rst quickref](http://docutils.sourceforge.net/docs/user/rst/quickref.html#escaping) also shows this is necessary in non-raw python strings.

addmessageheader doc

**Comment by nicolas33** [comment]
Hum, this is what I worried. Sorry, I think that the format of the comments in the code should cleanly statisfy the editors (vim, emacs) prior to the sphinx online documentation.

I can't think of an easy way to satisfy both at the same time for such a long comment. You might want to add a comment in the sources that the sphinx documentation is broken, though.

Please, close this request if you don't intend to add such statement in the source code.

Thanks for the clarification!

**Comment by mineo** [comment]
I've reverted the backslash-commit and added another one that adds a note to the documentation that for this method the proper docstring is only in the source. By enabling `sphinx.ext.viewcode` a link to that will be rendered right next to the method signature.

**Comment by nicolas33** [comment]
Looks much better!

Why did you based the first patch on the non-applied previous series? Could you squash them and re-send, please?

**Comment by mineo** [comment]
I only added 14d2eaa to make sure 14f3f82 doesn't contain any context from 0da616d.  14f3f82 cleanly applies on top of the `next` branch. I'm a bit confused about which commits you want me to squash, but if it makes it easier I could just close this pull request (as you've already applied the first 2 commits) and send a new one with just 14f3f82.

**Comment by nicolas33** [comment]
I'll look at that.

**Comment by nicolas33** [comment]
Applied last patch 14f3f82998.
Thank you!

**Pull request closed without merging**
