### PR TITLE
removed imaplib2 from this repo

### PR DESCRIPTION
**Pull request by xiaket**
As the current version of imaplib2.py have an import restriction on the
names used in this repo, we have to copy and paste it in for the time
being. I've filed a pull request to remove that barrier, and I hope it
would be accepted.

It is to be noted that two features that we've introduced in offlineimap
is lost for the time being:

    1. traceback printing.
    2. repr used around various messages.

So this patch should be carefully evaluated before it can be
incorporated into offlineimap's codebase.

### CODE REVIEW

**Comment by nicolas33** [comment]
imaplib2 is not widely packaged in distributions. I think the transition should be made more friendly: still embed imaplib2 and warn when fallbacking to the embedded version if it's not present in the OS.

**Comment by nicolas33** [comment]
Also, having imaplib2 out of OfflineIMAP means that different versions of it will be used. We have to check the version provided by the OS and having it to match the versions supported by OfflineIMAP.

**Comment by xiaket** [comment]
Yeah, you're right, I'll fix it.

**Comment by xiaket** [comment]
Sorry for the delay. It's Chinese new year here. 

I'm still looking for a way to check the version of the imaplib2 provided by the system. As we all can see in [bcoe's repo](https://github.com/bcoe/imaplib2/blob/master/imaplib2/imaplib2.py). The `__all__` in the file prevents the detection of the version of imaplib2. I've asked bcoe to remove that `__all__` from the repo, while his opinion is to follow the upstream, which is hosted in sourceforge. We can do some dirty walkaround here. But I doubt if that worth the trouble.

**Comment by nicolas33** [comment]
Yes, Piers is the author and maintainer. About that __version__ variable being not available, the only way to fix that is to send a patch to Piers.

About the intend in general, I'm still don't get why allowing external imaplib2 would be beneficial since it's just a single file to download. At least, I still don't think the benefits would worth the trouble nor the cost.

So, I'm closing. Thanks!

**Pull request closed without merging**
