### PR TITLE
XOAUTH2 implementation

### PR DESCRIPTION
**Pull request by Frizlab**
#72, rebased on master, commits signed off.

### CODE REVIEW

**Comment by nicolas33** [comment]
* Great but it's missing documentation, in offlineimap.conf at least.
* Please mark this feature experimental.
* Also, I'm not sure json and urllib are packaged with Python by all distribution maintainers. I guess it should be made optional and documented in both offlineimap.conf and README.md.

**Comment by Frizlab** [comment]
Documentation added. Not sure how to make json and urllib dependencies optional though. I just informed the reader about the required dependencies if they want to use XOAuth2 authentication.

**Comment by nicolas33** [comment]
Documentation looks well written but:
* I don't understand why it stands in its own repository example. We already have the `RemoteExample` repository section for this.
* `auth_mechanisms` configuration option is missing XOAUTH2.

Here's how to make a dependency optional:
```
if configuration.option == True: # enabled
    import blah
    #code using blah
```

Updating a git topic should be done in its own branch so that once updates are done you can squash the changes in the correct (already written) commits while keeping the previous history clean.

Thanks for the good work. ,-)

**Comment by Roguelazer** [comment]
`urllib` and `urllib2` are part of the Python core since Python 2.2 or so. `json` is part of Python core since 2.6.

**Comment by nicolas33** [comment]
Yes, I'm aware of this. What I'm not sure is that all distribution maintainers package them with Python.

@Frizlab : let's forget about making those optional. We will track if users complain.

**Comment by Frizlab** [comment]
Alright. I'll make the necessary changes soon.

**Comment by nicolas33** [comment]
Done.

**Comment by Frizlab** [comment]
Thanks! I don’t have time to do much these days… :/

**Pull request closed without merging**
