### PR TITLE
Systemd tweaks

### PR DESCRIPTION
**Pull request by hobarrera**
> This v1.0 template stands in `.github/`.

### Peer reviews

Trick to [fetch the pull request](https://help.github.com/articles/checking-out-pull-requests-locally): there is a (read-only) `refs/pull/` namespace.

``` bash
git fetch OFFICIAL_REPOSITORY_NAME pull/PULL_ID/head:LOCAL_BRANCH_NAME
```

### This PR

> Add character x `[x]`.

- [x] I've read the [DCO](http://www.offlineimap.org/doc/dco.html).
- [x] I've read the [Coding Guidelines](http://www.offlineimap.org/doc/CodingGuidelines.html)
- [x] The relevant information about the changes stands in the commit message, not here in the message of the pull request.
- [x] Code changes follow the style of the files they change.
- [x] Code is tested (provide details).

### Additional information

Granular explanation for each change is explained in the commit message. There's a small mix of:

* Follow conventions
* Improve docs
* Simplify things
* Remove broken setting (that got the entire file rejected)

### CODE REVIEW

**Comment by nicolas33** [comment]
Great series of patches. Applied.

Thank you much!

**Comment by hobarrera** [comment]
np! Thanks!

**Comment by benutzer193** [comment]
@hobarrera Are you sure about `Restart=`, it should also work for one shot units if they exit with a non clean exit code, or do I misinterpret the [docs](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=)?

**Comment by hobarrera** [comment]
This PR was targeting `next` so you could've just hit merge and avoid doing it manually. 😉

**Comment by benutzer193** [comment]
@hobarrera 
Good PR, was also wondering about the mail.target as it doesn't add any features atm, but thought someone had a reason for it and so did just leave it.

I falsely assumed restart on failure would be supported by oneshot units (which would make sense), I can't find anything in the docs which negates that, [but it seem I am not the only one assuming that](https://github.com/systemd/systemd/issues/2582). Thanks for pushing the fix.
About the naming: I thought oneshot is redundant and confusing for a timer unit, so I chose deliberately against the recommendation (*if I am not mistaken it's only a [recommendation](https://www.freedesktop.org/software/systemd/man/systemd.timer.html#Unit=) not a convention).

@nicolas33 :
About syslog, do we even need that UI? If you need to save stdout to a file you could just redirect the output?

**Comment by hobarrera** [comment]
>Good PR

Thanks!

> I falsely assumed restart on failure would be supported by oneshot units (which would make sense), I can't find anything in the docs which negates that, but it seem I am not the only one assuming that. Thanks for pushing the fix.

I **think** I read it in the docs, but maybe I simply discovered it my writing some unit file that failed and learned from that.

I wonder if `OnFailure=` can be used for this (though the lack of sleep might lead to thrashing).

>  About syslog, do we even need that UI? If you need to save stdout to a file you could just redirect the output?

`syslog` will also log to syslog/journalctl if you run it interactively (eg: via a shell).

**Comment by benutzer193** [comment]
> I wonder if OnFailure= can be used for this (though the lack of sleep might lead to thrashing).
Perhaps. But as the timer runs every 15m, failing sometimes shouldn't be to bad and I now (after your PR) think it's best without any additional restart possibility. I also wonder if [`OnUnitInactiveSec=`](https://www.freedesktop.org/software/systemd/man/systemd.timer.html#OnActiveSec=) even recognizes restarted services.

> syslog will also log to syslog/journalctl if you run it interactively (eg: via a shell).
In this case a simple `| tee <logfile>` should work, but I guess it's nice to have. :smiley: And why interactive + a noninteractive UI?

**Comment by hobarrera** [comment]
> And why running interactively + a noninteractive UI?

Yeah, bad example.
It's still useful for non-systemd OSs (eg: BSDs, weird linuxes, maybe macOS). The app itself should log into syslog itself (rather than the service manager handle it).

Not sure if it's a common scenario or not though.

**Comment by nicolas33** [comment]
> Not sure if it's a common scenario or not though.

syslog was implemented before systemd was out. Today, it's still useful for some use cases when offlineimap is started by cron or from a wrapper script (not forcefully in shell). Also, rare users have systemd but avoid journald in favour of syslog.

**Comment by hobarrera** [comment]
Yeah, but we still have the BSD and possibly macOS users. But what I'm unsure of is if they actually use syslog for this (since syslog tends to be system-wide, and offlineimap is user-scope, so as to say).

**Comment by nicolas33** [comment]
> Yeah, but we still have the BSD and possibly macOS users. But what I'm unsure of is if they actually use syslog for this (since syslog tends to be system-wide, and offlineimap is user-scope, so as to say).

Sure, syslog can be used for those systems and helps making offlineimap more portable. I did not want to repeat your point. :-)

**Comment by nicolas33** [comment]
> But as the timer runs every 15m, failing sometimes shouldn't be to bad and I now (after your PR) think it's best without any additional restart possibility

We should not assume values. We provide defaults but distrib maintainers and users can (and will) change them to their own.

The best we can do is not to **define** the values for all the possible use cases. This won't work and will make things more confusing for some users. What we should do is to provide "good" defaults for *most use cases* and document the most relevant options with all the side effects and requirements, even for those we decide to **not** enable in our samples.

Of course, this requires good systemd skills.

**Comment by benutzer193** [comment]
> We should not assume values. We provide defaults but distrib maintainers and users can (and will) change them to their own.

Yes we should not. But, as 15m is the default we should make sure, that this value works for most use cases. What I wanted to say was, that even if there are infrequent failings, it shouldn't matter for a default value of 15m for most use cases.

Perhaps it is a good idea to document, why `Restart=` is not available for oneshot units, as it is used on the other units and so could lead to people trying to enable it for the oneshot units?

**Comment by nicolas33** [comment]
> Yes we should not. But, as 15m is the default we should make sure, that this value works for most use cases. What I wanted to say was, that even if there are infrequent failings, it shouldn't matter for a default value of 15m for most use cases.

Got it!



> Perhaps it is a good idea to document, why Restart= is not available for oneshot units, as it is used on the other units and so could lead to people trying to enable it for the oneshot units?

Yes, I think this would be great.

**Pull request closed without merging**
