### PR TITLE
Optional TLS

### PR DESCRIPTION
**Pull request by mativs**
I have just adapt the code to fulfil this old debian patch I've found on internet written by Kapil Hari Paranjape <kapil@imsc.res.in>. You can find more information in this link <http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=681494>

>I need to connect to a badly configured server that advertises STARTTLS
>but is not properly configured for it :(
>
>So I created an option 'tls' which allows me to disable the use of
>STARTTLS for this server.

Hope it helps

### CODE REVIEW

**Comment by nicolas33** [comment]
I hate such patches merged by distribution maintainers not submitting upstream. And the original patch is not signed.

@mativs : Ssnce you know the issue, could you please rewrite a fresh patch from scratch, sign your work and re-submit?

**Comment by nicolas33** [comment]
Good point, closing.

**Comment by tangxinfa** [comment]
I encountered this problem on our company's mail server, what is the progress of this problem?

**Comment by nicolas33** [comment]
The latest work in this area is #111 but it's not addressing this feature.

**Comment by tangxinfa** [comment]
Thanks, the starttls option fixed this problem

    starttls = no

See https://github.com/OfflineIMAP/offlineimap/issues/207 for more information.

**Pull request closed without merging**
