### PR TITLE
New tls

### PR DESCRIPTION
**Pull request by mathstuf**
---
Also removes old, broken versions. TLSv1 should be removed too, but then there's no overlap with old versions.

### CODE REVIEW

**Comment by nicolas33** [comment]
Not sure users won't cry about SSLv2 et 3.
Please, sign your patches.

**Comment by mathstuf** [comment]
Added signoffs. Feel free to take just the first patch; the second is a vain hope that those can go away someday. Thought I had put that somewhere on here, but I guess it was late.

**Comment by BlacklightShining** [comment]
Yes, please. I've been looking all over for an MRA that I can configure to refuse plaintext and TLS versions that are too old.

**Comment by mathstuf** [comment]
Updated to be less opinionated :) . Needs more testing now too

**Comment by nicolas33** [comment]
I'm sorry I didn't noticed the changes in imaplib2. Please, submit the changes of imaplib2 upstream so I can merge.
Otherwise, it looks good to me.

**Comment by BlacklightShining** [comment]
@nicolas33 Upstream as in [nicolas33/offlineimap](https://github.com/nicolas33/offlineimap)? Because that has a note saying development's moved _here._

**Comment by mathstuf** [comment]
No, he means the [imaplib2 project](http://sourceforge.net/projects/imaplib2/) upstream. I'll look at doing that, but why offlineimap is shipping a copy rather than using a system version is another question…

**Comment by nicolas33** [comment]
It is historical and has advantages because using system imalib2 means dealing with a lot of versions.

**Comment by mathstuf** [comment]
Patches sent upstream. Should be available [here](http://sourceforge.net/p/imaplib2/mailman/imaplib2-devel/?viewmonth=201509) once they go through moderation.

**Comment by mathstuf** [comment]
Once the patch lands, cherry-picking the `HEAD` of this PR should suffice (or ping me and I'll rebase).

**Comment by mathstuf** [comment]
Amended the last commit to read the option out of the right block.

**Comment by nicolas33** [comment]
Nice! Feel free to remind to merge this patch once the new version of imaplib2 is out.

**Comment by nicolas33** [comment]
@mathstuf: since the patch was changed and merged upstream, should I apply this topic as-is or does it requires changes, too?

**Comment by mathstuf** [comment]
Looks like upstream touched up my patch a bit. How do you usually update imaplib2?

**Comment by nicolas33** [comment]
I've already applied imaplib2 v2.49 (see #cc3cbaea05af8ae6eed788a5fc81c561ee038324) in the `next` branch. I track imaplib2 with Git. So, I do a `cp` of the file. :-)

**Comment by mathstuf** [comment]
OK, I've rebased on top of `develop`. I added `tls_level` to another call. Should be good to go if everything checks out. Thanks.

**Comment by nicolas33** [comment]
"If everything checks out"? Did you test the code?

**Comment by mathstuf** [comment]
Meant it in the review sense, but I hadn't after the rebase. Seems I had missed some patches from my editing anyways (was editing right in the install tree rather than the source tree). I fixed those errors, but now I'm hitting errors related to `getoauth2_request_url` because I don't have my accounts set up to use it (but it doesn't fallback gracefully).

**Comment by nicolas33** [comment]
Nah. I disagree with the last changes. The previous submit look better. Why did you change `getconf` to `getconfboolean` which is not a boolean option?

**Comment by mathstuf** [comment]
It was `getconfboolean` before and isn't now? Other change was removing the tls_level import.

**Comment by nicolas33** [comment]
About the OAuth2 fallback, you can disable this feature in the `auth_mechanisms` configuration option. I will disable it by default.

**Comment by nicolas33** [comment]
Removing XOAUTH2 in the configuration option. Fix it in the code I get 

```
ERROR: While attempting to sync account 'nis'
  __init__() got an unexpected keyword argument 'tls_level'

Traceback:
  File "/home/nicolas/dev/official_packages/gitrepos/offlineimap/offlineimap/accounts.py", line 263, in syncrunner
    self.__sync()
  File "/home/nicolas/dev/official_packages/gitrepos/offlineimap/offlineimap/accounts.py", line 326, in __sync
    remoterepos.getfolders()
  File "/home/nicolas/dev/official_packages/gitrepos/offlineimap/offlineimap/repository/IMAP.py", line 384, in getfolders
    imapobj = self.imapserver.acquireconnection()
  File "/home/nicolas/dev/official_packages/gitrepos/offlineimap/offlineimap/imapserver.py", line 490, in acquireconnection
    tls_level=self.tlslevel,
  File "/home/nicolas/dev/official_packages/gitrepos/offlineimap/offlineimap/imaplibutil.py", line 215, in __init__
    IMAP4.__init__(self, *args, **kwargs)
```

**Comment by nicolas33** [comment]
Fixed the XOAUTH2 issue: #258.

**Comment by mathstuf** [comment]
OK, removed the `tls_level` from the non-SSL call.

**Comment by nicolas33** [comment]
Thank you, applied. I've added some minor changes in `offlineimap.conf`.

**Comment by nicolas33** [comment]
Ah, and marked this feature experimental for now. :-)

**Pull request closed without merging**
