### PR TITLE
mkdir -p alike folder creation

### PR DESCRIPTION
**Pull request by altendky**
### This PR

- [x] I've read the [DCO](http://www.offlineimap.org/doc/dco.html).
- [x] I've read the [Coding Guidelines](http://www.offlineimap.org/doc/CodingGuidelines.html)
- [x] The relevant informations about the changes stands in the commit message, not here in the message of the pull request.
- [x] Code changes follow the style of the files they change.
- [x] Code is tested (provide details).

### References

- Issue #335
- Issue #598

### CODE REVIEW

**Comment by altendky** [comment]
@nicolas33, here's my fairly naive start at a solution.  It solves my situation and successfully created the nested labels.  I'll note that I also had to remove 'extra' spaces from a few folders because Gmail complained.  Trailing spaces and double spaces between words to be specific.  I figure that's something to be addressed manually or in a nametrans, not to be built into offlineimap.

I don't foresee a specific future use of this for myself but I don't want to leave this hanging either if others are interested.  Let me know how far off this is from something that would be accepted and we can see if I'll jump through whatever hoops to reach that point.

Cheers,
-kyle

**Comment by nicolas33** [comment]
@altendky This code looks good enough to me. We might like to avoid trying to create the same path twice though.

**Comment by altendky** [comment]
@nicolas33, at what level?  I didn't bother with an existence check prior to the creation due to the potential race condition.  But I guess as is you have a race if a layer is created and something else deletes it before the next layer is created...  Are you hoping for less of a performance hit?  or?

**Comment by nicolas33** [comment]
> I didn't bother with an existence check prior to the creation due to the potential race condition.

Fair enough. I was thinking about avoiding our own races in creating upper levels (eg. a/b/i and a/b/j will try to create a and b twice).
Anyway, folder creation is not a daily operation so I'm fine with the current code. If we'd like to increase performance there would be other enhancements to do first, BTW. Also, this fix comes with much more benefits than drawbacks.

Let's merge this PR. Do you want to remove the WIP flag yourself or I do it at merge time?

**Comment by nicolas33** [comment]
@altendky ?

**Comment by altendky** [comment]
@nicolas33, my apologies, I'm pretty booked.  I do plan to get back to this.  If you are happy as is, go for the merge.  I had the impression I should be signing my commit and maybe some other stuff as well which I hadn't reviewed in detail.

**Comment by nicolas33** [comment]
ok, no hurry. We have time.

**Comment by altendky** [comment]
@nicolas33, alrighty I think I got it all.

Side note, not sure if it's on purpose but if you put `[ ]` instead of `[]` in the PR template the checkboxes would be checkable in the GUI.

- [] from: `- []`
- [ ] from: `- [ ]`

**Comment by nicolas33** [comment]
Didn't know this. Updated.

Patch applied. Thank you much!

**Pull request closed without merging**
