### PR TITLE
Fix expired oauth2_access_token

### PR DESCRIPTION
**Pull request by frodeaa**
### This PR

- [x] I've read the [DCO](http://www.offlineimap.org/doc/dco.html).
- [x] I've read the [Coding Guidelines](http://www.offlineimap.org/doc/CodingGuidelines.html)
- [x] The relevant informations about the changes stands in the commit message, not here in the message of the pull request.
- [x] Code changes follow the style of the files they change.
- [x] Code is tested (provide details).

### References

- Issue #536

### CODE REVIEW

**Comment by nicolas33** [comment]
Applied. Thank you very much.

**Comment by nicolas33** [comment]
This commit broke the tests. Please, check https://travis-ci.org/OfflineIMAP/offlineimap

cc'ing @chris001

**Comment by frodeaa** [comment]
@nicolas33 difficult to see what the issue is, what is the difference between the jobs?

**Comment by frodeaa** [comment]
seems strange that my changes should cause PLAIN authentication to fail
https://travis-ci.org/OfflineIMAP/offlineimap/jobs/456704571#L516

**Comment by nicolas33** [comment]
@chris001 Could you confirm that the accounts are still activated, please ?

**Comment by nicolas33** [comment]
@frodeaa @chris001 

I've triggered a new build today and it looks to pass, now. Don't know why it failed.

https://travis-ci.org/OfflineIMAP/offlineimap/builds/457185716

Sorry for the noise.

**Pull request closed without merging**
