### PR TITLE
When using StartTLS verify the CA and/or fingerprint

### PR DESCRIPTION
**Pull request by muggenhor**
Perform CA/fingerprint validation for StartTLS as well.

### CODE REVIEW

**Comment by nicolas33** [comment]
Applied into next, thanks.

**Comment by nicolas33** [comment]
I had to remove this patch, sorry. The reasons are:
* a call to self.verficert instead of self.__verficert
* looks like this patch enable StartTLS in all cases (even if user don't want this feature at all)

I guess you can't go without adding a starttls configuration option.

**Comment by nicolas33** [comment]
@muggenhor : do you still intend to get this merged or should I close it?

**Comment by muggenhor** [comment]
@nicolas33 I'm afraid I don't have the time right now nor in the foreseeable future, so closing is ok.

**Comment by nicolas33** [comment]
I repoen and mark it "need contributor" so that anybody else interested catch it and work on this.

**Comment by muggenhor** [comment]
even better!

**Comment by nicolas33** [comment]
Put this topic into `pu`.

**Comment by nicolas33** [comment]
The intend is good. However, the implementation relies on the ssl configuration options. I don't think users configuring SSL are using STARTTLS.
So unless there are server side limitations I'm not aware, I'm closing this PR.

**Pull request closed without merging**
