### PR TITLE
update readme to give an hint about LInux distros

### PR DESCRIPTION
**Pull request by MalloZup**
Update doc with Linux OS

### CODE REVIEW

**Comment by MalloZup** [comment]
@chris001  if you have any question just feel free to ping me. TIA

**Comment by nicolas33** [comment]
Applied. Thank you.

**Comment by MalloZup** [comment]
@nicolas33 can you give me a pointer of the changes? TIA

**Comment by MalloZup** [comment]
ok found here. https://github.com/OfflineIMAP/offlineimap/tree/next#downloads thx

**Pull request closed without merging**
