### PR TITLE
Systemd touchups

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by mathstuf** [comment]
I finally pulled the trigger on converting my setup over to `systemd --user` and had forgotten about the issue here about it. Here's some minor changes and documentation for them.

**Comment by nicolas33** [comment]
Good patches. Please, read the [dco](http://offlineimap.org/doc/dco.html) so I can apply.
Thank you!

**Comment by mathstuf** [comment]
Whoops, missed `--signoff`. Commit amended. Doesn't seem to be a config value I can set to automatically do this so I don't forget in the future?

**Comment by nicolas33** [comment]
I think you amended the last commit but not the previous. Adding it myself since you clearly intend to sign.
I'm not aware of such an option in git, you might want to set an alias.
Thanks.

**Comment by mathstuf** [comment]
Ah, yeah. Missed that it was two commits then too. Juggling too many things :) . FWIW, yes, I approve the signoff. Digging deeper, they mention that it must be an explicit action, so it seems that an alias would be the easiest.

**Pull request closed without merging**
