### PR TITLE
Pass username through in GSSAPI connections

### PR DESCRIPTION
**Pull request by frozencemetery**
Fix bug in GSSAPI auth where the username was not being negotiated.

Signed-off-by: Robbie Harwood <rharwood@redhat.com>

> This v1.1 template stands in `.github/`.

### This PR

> Add character x `[x]`.

- [x] I've read the [DCO](http://www.offlineimap.org/doc/dco.html).
- [x] I've read the [Coding Guidelines](http://www.offlineimap.org/doc/CodingGuidelines.html)
- [x] The relevant informations about the changes stands in the commit message, not here in the message of the pull request.
- [x] Code changes follow the style of the files they change.
- [x] Code is tested (provide details).

### References

- Issue #541 

### Additional information

Code works on my server, but I never manifested the bug.

If there's a better reference for the behavior we implement here, please feel free to update my comment to point to it.

### CODE REVIEW

**Comment by frozencemetery** [comment]
(I don't think these CI errors are related.)

**Comment by nicolas33** [comment]
Yes, don't worry about the CI errors. It's failing for other reasons. I'll disable this because this might disturb other contributors.

**Comment by lenormf** [comment]
It works!

```
OfflineIMAP 7.2.0
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.15, OpenSSL 1.1.0h  27 Mar 2018
Debug mode: Forcing to singlethreaded.
Now debugging for imap: IMAP protocol debugging
Now debugging for : Other offlineimap related sync messages
Account sync abc:
 [imap]: Using authentication mechanisms ['GSSAPI', 'XOAUTH2', 'CRAM-MD5', 'PLAIN', 'LOGIN']
 *** Processing account abc
 Establishing connection to imap.abclabs.ru:993 (RemoteAbc)
 [imap]: RemoteAbc: level 'tls_compat', version 'None'
 [imap]: Attempting GSSAPI authentication
 []: Copying folder structure from RemoteAbc to LocalAbc
 Syncing Archive: IMAP -> Maildir
 Loading message list for IMAP[Archive]
 Loading message list for Maildir[Archive]
 Message list for Maildir[Archive] loaded: 0 messages
 Syncing messages IMAP[Archive] -> Maildir[Archive]
 Syncing messages Maildir[Archive] -> IMAP[Archive]
 Syncing Drafts: IMAP -> Maildir
 Loading message list for IMAP[Drafts]
 Loading message list for Maildir[Drafts]
 Message list for Maildir[Drafts] loaded: 0 messages
 Syncing messages IMAP[Drafts] -> Maildir[Drafts]
 Syncing messages Maildir[Drafts] -> IMAP[Drafts]
 Syncing INBOX: IMAP -> Maildir
 Loading message list for IMAP[INBOX]
 [imap]: calling imaplib2 fetch command: '783:3236' (FLAGS UID INTERNALDATE)

[…]

 Message list for IMAP[INBOX] loaded: 2454 messages
 Loading message list for Maildir[INBOX]
 Message list for Maildir[INBOX] loaded: 2454 messages
 Syncing messages IMAP[INBOX] -> Maildir[INBOX]
 Syncing messages Maildir[INBOX] -> IMAP[INBOX]
 Adding flag S to 1 messages on INBOX
 [imap]: __options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '3259'}
 Adding flag R to 1 messages on INBOX
 [imap]: __options2hash returning: {'FLAGS': '(\\Answered \\Seen)', 'UID': '3259'}



 Syncing Sent: IMAP -> Maildir
 Loading message list for IMAP[Sent]

[…]

 Message list for IMAP[Sent] loaded: 571 messages
 Loading message list for Maildir[Sent]
 Message list for Maildir[Sent] loaded: 571 messages
 Syncing messages IMAP[Sent] -> Maildir[Sent]
 Syncing messages Maildir[Sent] -> IMAP[Sent]
 Syncing Spam: IMAP -> Maildir
 Loading message list for IMAP[Spam]
 Loading message list for Maildir[Spam]
 Message list for Maildir[Spam] loaded: 0 messages
 Syncing messages IMAP[Spam] -> Maildir[Spam]
 Syncing messages Maildir[Spam] -> IMAP[Spam]
 Syncing Trash: IMAP -> Maildir
 Loading message list for IMAP[Trash]
 Loading message list for Maildir[Trash]
 Message list for Maildir[Trash] loaded: 0 messages
 Syncing messages IMAP[Trash] -> Maildir[Trash]
 Syncing messages Maildir[Trash] -> IMAP[Trash]
 Calling hook: notmuch new
 Hook stdout: Processed 3 total files in almost no time.
No new mail. Detected 3 file renames.

Hook stderr:

 Hook return code: 0
 *** Finished account 'abc' in 0:06
```

**Comment by nicolas33** [comment]
Thank you much.
Patch applied.

**Comment by chris001** [comment]
The CI was failing because of security.  A PR from a fork external to this repo (in this case, the fork "frozencemetery:pykerberos-is-bad"), isn't allowed to get the decrypted environment variables which the CI test scripts use to run the tests connecting to various real IMAP mail servers.  These environment variables are the private secure email account login credentials. So, will have to find some way around this, while keeping CI enabled for all branches here in this main repo. One way might be to make new "test" branch for each PR coming from an external repo, merge that PR into that "test" branch, the CI tests will run, and give their results. If the results are good, then that branch can be merged into "next".

**Comment by nicolas33** [comment]
Yes. The other way I'm taking is to use the "next" itself for the tests. This branch already provides the opportunity to rework a failing patch. I'm not convinced we need a more complicated workflow for the current workload. ,-)

**Pull request closed without merging**
